#!/bin/sh
# mult <-> Claude Code generation-scoped status bridge.
#
# mult creates an owner-private append-only journal and exports the complete
# durable session identity. This hook appends one bounded lifecycle transition;
# the TUI validates every field and the daemon remains authoritative.
set -u

# Claude Code delivers hook JSON on stdin. Status boundaries come from the
# configured hook event, not from arbitrary PTY bytes, so the body is drained
# and deliberately ignored.
cat >/dev/null 2>&1 || true

status=${1:-}
path=${MULT_AGENT_STATUS_PATH:-}
version=${MULT_AGENT_STATUS_VERSION:-}
namespace=${MULT_AGENT_NAMESPACE:-}
token=${MULT_AGENT_SESSION_TOKEN:-}
chat=${MULT_AGENT_CHAT_ID:-}
kind=${MULT_AGENT_KIND:-}
generation=${MULT_AGENT_GENERATION:-}

[ -n "$status" ] || exit 0
[ -n "$path" ] || exit 0
[ -n "$version" ] || exit 0
[ -n "$namespace" ] || exit 0
[ -n "$token" ] || exit 0
[ -n "$chat" ] || exit 0
[ -n "$kind" ] || exit 0
[ -n "$generation" ] || exit 0

# All interpolated identity values are generated by mult from fixed
# hexadecimal/numeric vocabularies. The status argument is fixed in generated
# settings. Append atomically for these sub-PIPE_BUF records and never create a
# missing parent/file, so a cleaned stale generation cannot be resurrected.
[ -f "$path" ] || exit 0
size=$(wc -c <"$path" 2>/dev/null || printf '%s' 1048577)
[ "$size" -lt 1048576 ] 2>/dev/null || exit 0
printf '{"version":%s,"namespace":"%s","sessionToken":"%s","chatId":"%s","agentKind":"%s","generation":"%s","status":"%s"}\n' \
  "$version" "$namespace" "$token" "$chat" "$kind" "$generation" "$status" >>"$path" 2>/dev/null || true
exit 0
